apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-app
  namespace: portfolio
subjects:
  - kind: ServiceAccount
    name: portfolio-app
    namespace: portfolio
roleRef:
  kind: Role
  name: portfolio-app
  apiGroup: rbac.authorization.k8s.io
